<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.9.5 on win32)" generated="20231002 14:35:56.322" rpa="false" schemaversion="4">
<suite id="s1" name="Test" source="C:\Users\1809569\coderepository\amazon\Testcases\test.robot">
<test id="s1-t1" name="check valid login" line="7">
<kw name="Start browser and maximize" library="Resources1">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${url}</arg>
<arg>${browser}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20231002 14:35:56.560" level="INFO">Opening browser 'Edge' to base url 'https://rahulshettyacademy.com/loginpagePractise/'.</msg>
<msg timestamp="20231002 14:36:14.197" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550AA24220&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot</msg>
<msg timestamp="20231002 14:36:18.310" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550AA24520&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot</msg>
<msg timestamp="20231002 14:36:22.377" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550A5C6A30&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot</msg>
<msg timestamp="20231002 14:36:26.488" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55659): Max retries exceeded with url: /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550AA24730&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<msg timestamp="20231002 14:36:26.491" level="FAIL">ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))</msg>
<status status="FAIL" starttime="20231002 14:35:56.560" endtime="20231002 14:36:26.516"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="NOT RUN" starttime="20231002 14:36:26.517" endtime="20231002 14:36:26.517"/>
</kw>
<status status="FAIL" starttime="20231002 14:35:56.560" endtime="20231002 14:36:26.518"/>
</kw>
<kw name="Set Selenium Speed" library="SeleniumLibrary">
<arg>1seconds</arg>
<doc>Sets the delay that is waited after each Selenium command.</doc>
<status status="NOT RUN" starttime="20231002 14:36:26.519" endtime="20231002 14:36:26.519"/>
</kw>
<kw name="Open Context Menu" library="SeleniumLibrary">
<arg>xpath://input[@id='username']</arg>
<doc>Opens the context menu on the element identified by ``locator``.</doc>
<status status="NOT RUN" starttime="20231002 14:36:26.520" endtime="20231002 14:36:26.521"/>
</kw>
<kw name="Enter username and password" library="Resources1">
<arg>rahulshettyacademy</arg>
<arg>learning</arg>
<status status="NOT RUN" starttime="20231002 14:36:26.521" endtime="20231002 14:36:26.521"/>
</kw>
<kw name="Select From List By Index" library="SeleniumLibrary">
<arg>xpath://select[@class='form-control']</arg>
<arg>1</arg>
<doc>Selects options from selection list ``locator`` by ``indexes``.</doc>
<status status="NOT RUN" starttime="20231002 14:36:26.522" endtime="20231002 14:36:26.522"/>
</kw>
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="NOT RUN" starttime="20231002 14:36:26.523" endtime="20231002 14:36:26.523"/>
</kw>
<status status="FAIL" starttime="20231002 14:35:56.559" endtime="20231002 14:36:26.524">ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20231002 14:35:56.324" endtime="20231002 14:36:26.530"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231002 14:36:14.197" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550AA24220&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot</msg>
<msg timestamp="20231002 14:36:18.310" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550AA24520&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot</msg>
<msg timestamp="20231002 14:36:22.377" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550A5C6A30&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot</msg>
<msg timestamp="20231002 14:36:26.488" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55659): Max retries exceeded with url: /session/4b09a74eff3ebbb9dcf3d2be4c0faf62/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001550AA24730&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
</errors>
</robot>
